# Generated by Django 4.2.7 on 2023-11-21 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigosBarra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_generado', models.CharField(max_length=255)),
                ('cod_fecha', models.DateField(auto_now_add=True)),
                ('cod_imagen', models.ImageField(upload_to='codigos_barra/')),
                ('fk_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuarios')),
            ],
        ),
    ]
