# Generated by Django 4.2.7 on 2023-11-18 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usu_nombre', models.CharField(max_length=25)),
                ('usu_apellido', models.CharField(max_length=25)),
                ('usu_rut', models.CharField(max_length=10)),
                ('usu_fecha', models.DateField(auto_now_add=True)),
                ('usu_tipo', models.IntegerField(choices=[(0, 'Funcionario'), (1, 'Estudiante')])),
            ],
        ),
    ]
