# Generated by Django 4.2.7 on 2023-12-02 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuarios_dentro_estacionamiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='usu_tipo',
            field=models.IntegerField(choices=[(0, 'Funcionario'), (1, 'Estudiante'), (2, 'Estudiante')]),
        ),
    ]
