# Generated by Django 4.2.7 on 2023-12-01 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CuposEstacionamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cupo_funcionarios', models.PositiveIntegerField(default=30)),
                ('cupo_estudiantes', models.PositiveIntegerField(default=60)),
                ('cupo_visitas', models.PositiveIntegerField(default=10)),
            ],
        ),
    ]
