# Generated by Django 4.2.7 on 2023-12-01 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamientos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estacionamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('configuracion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='estacionamientos.cuposestacionamiento')),
            ],
        ),
    ]
