# Generated by Django 4.2.7 on 2023-12-01 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamientos', '0002_estacionamiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuposestacionamiento',
            name='cupo_estudiantes_actual',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cuposestacionamiento',
            name='cupo_funcionarios_actual',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cuposestacionamiento',
            name='cupo_visitas_actual',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
