# Generated by Django 4.2.7 on 2023-12-02 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamientos', '0003_cuposestacionamiento_cupo_estudiantes_actual_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuposestacionamiento',
            name='cupo_estudiantes_actual',
        ),
        migrations.RemoveField(
            model_name='cuposestacionamiento',
            name='cupo_funcionarios_actual',
        ),
        migrations.RemoveField(
            model_name='cuposestacionamiento',
            name='cupo_visitas_actual',
        ),
    ]
